### ISSUE TITLE
无法访问慢查询表

### ISSUE THREAD

**Issue by sh-hanson** [SnailDev/SnailDev.MongoStudio#3]
当访问慢查询表system.profile时，服务直接报错退出，报错信息如下：
the options [uri_decode_auth] is not supported
/root/SnailDev.MongoStudio/src/MongoStudio/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

TypeError: Cannot read property 'forEach' of null
    at /root/SnailDev.MongoStudio/src/MongoStudio/util/db.js:149:23
    at err (/root/SnailDev.MongoStudio/src/MongoStudio/node_modules/mongodb/lib/utils.js:415:14)
    at executeCallback (/root/SnailDev.MongoStudio/src/MongoStudio/node_modules/mongodb/lib/utils.js:404:25)
    at handleCallback (/root/SnailDev.MongoStudio/src/MongoStudio/node_modules/mongodb/lib/utils.js:128:55)
    at cursor._endSession.cursor._endSession (/root/SnailDev.MongoStudio/src/MongoStudio/node_modules/mongodb/lib/operations/cursor_ops.js:214:38)
    at Cursor._endSession (/root/SnailDev.MongoStudio/src/MongoStudio/node_modules/mongodb-core/lib/cursor.js:193:5)
    at Cursor._endSession (/root/SnailDev.MongoStudio/src/MongoStudio/node_modules/mongodb/lib/cursor.js:226:59)
    at cursor._next (/root/SnailDev.MongoStudio/src/MongoStudio/node_modules/mongodb/lib/operations/cursor_ops.js:214:20)
    at handleCallback (/root/SnailDev.MongoStudio/src/MongoStudio/node_modules/mongodb-core/lib/cursor.js:202:5)
    at /root/SnailDev.MongoStudio/src/MongoStudio/node_modules/mongodb-core/lib/cursor.js:674:23
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mongostudio@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mongostudio@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-01T07_03_58_353Z-debug.log

**Comment by SnailDev** [comment]
这个问题就是 密码中@ 号问题，将于@符号统一处理。
